version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: agent-bridge-api
    ports:
      - "8080:8080"
    volumes:
      - ../app:/app/app
      - ../requirements.txt:/app/requirements.txt
    env_file:
      - ../.env
